- hosts: both

  tasks:
    - name: Delete user sansa
      ansible.builtin.user:
        name: sansa
        state: absent
        remove: yes
      become: yes
      tags: [users, delete]

    - name: Delete user jaime
      ansible.builtin.user:
        name: jaime
        state: absent
        remove: yes
      become: yes
      tags: [users, delete]

    - name: Delete user testuser
      ansible.builtin.user:
        name: testuser
        state: absent
        remove: yes
      become: yes
      tags: [users, delete]
