- hosts: both

  tasks:
    - name: Delete user sansa
      ansible.builtin.user:
        name: Ostapa
        state: absent
        remove: yes
      become: yes
      tags: [users, delete]

    - name: Delete user jaime
      ansible.builtin.user:
        name: Papafan
        state: absent
        remove: yes
      become: yes
      tags: [users, delete]
