# применили фильтрацию
- hosts: local
  gather_facts: no
  vars:
    numbers: [1,2,2,3,3,4]
  tasks:
    - name: Touch the Winter file
      ansible.builtin.file:
        path: "{{ numbers | min }}.txt"
        state: touch
#      become: true
