- hosts: all
  gather_facts: no
  vars:
    db_name: dimanvaz_db
    db_user: dimanvaz
  tasks:
    - name: Get sql files list
      find:
        paths: sql
        patterns: '*.sql'
      register: sql_files

    - name: Prepare file list
      set_fact:
        sql_files_paths: "{{ sql_files['files'] | sort(attribute='path') | map(attribute='path') }}"

    # For debug
    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: sql_files_paths
        verbosity: 1

    # BEGIN (write your solution here) создать базу, выполнять запросы
    - name: Создание новой базы данных
      community.postgresql.postgresql_db:
        name: "{{ db_name }}"
        state: present
        owner: "{{ db_user }}"
        login_user: "{{ db_user }}"

    - name: Run queries from "{{ item }}"
      community.postgresql.postgresql_query:
          login_user: "{{ db_user }}"
          db: "{{ db_name }}"
          path_to_script: "{{ item }}"  # элемент массива путей, т.е. конкретный путь
          as_single_query: yes
      with_items: "{{ sql_files_paths }}"  # массив путей - переменная, определённая выше
    # END


    - name: Select first 5 topics for check result
      community.postgresql.postgresql_query:
        login_user: "{{ db_user }}"
        db: "{{ db_name }}"
        query: SELECT * FROM topics LIMIT 5
      register: select_topics_result

    # For debug
    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: select_topics_result
        verbosity: 1

    - name: Check result
      fail:
        msg: "Expected `5` but was `{{ select_topics_result['rowcount'] }}`"
      when: select_topics_result is not defined or select_topics_result['rowcount'] != 5
